### ISSUE TITLE
Does the driver support Gemini Lake?

### ISSUE THREAD

**Issue by dmitryermilov** [intel/media-driver#376]

**Comment by XinfengZhang** [comment]
not yet. the device ID should already added, but not fully test.

**Comment by zcwang** [comment]
Hi All,
Does intel-media-19.4.0 (or the latest upstream of media-driver) support GLK in Linux?
https://github.com/intel/media-driver/releases/tag/intel-media-19.4.0r

Thanks!
Gary

**Comment by zcwang** [comment]
[GST-error-in-GLK_gary0406.log](https://github.com/intel/media-driver/files/4439260/GST-error-in-GLK_gary0406.log)
Error caused by GST plug-in vaapi in GLK/Ubuntu 18.04

"gst-launch-1.0 -ev videotestsrc num-buffers=600 ! video/x-raw,width=3840,height=2160,framerate=30/1 ! vaapih264enc ! h264parse ! mp4mux ! filesink location=test.mp4"

**Comment by zcwang** [comment]
Related issue for reference
https://github.com/intel/media-driver/issues/897

**Comment by THX723** [comment]
@XinfengZhang @dmitryermilov Curious if a timeline has been established for when GLK will be fully integrated and tested in the media driver?

**Comment by XinfengZhang** [comment]
#1005 should fixed some issue with GLK

**Comment by XinfengZhang** [comment]
@zcwang hi Gary, have you tried PR #1005 ?

**Comment by Jexu** [comment]
As mentiosned above, this issue should have been fixed. So i will close this issue and feel free to re-open it agsin if you have any other questions. Thanks
