### ISSUE TITLE
creating surfaces for I420 with VA_SURFACE_ATTRIB_MEM_TYPE_USER_PTR

### ISSUE THREAD

**Issue by shakeeb80** [intel/media-driver#701]
I am trying to use vaCreateSurfaces to create an I420 surface with VA_SURFACE_ATTRIB_MEM_TYPE_USER_PTR memory type. However it looks like any multi plane surface is not supported. I am filling VASurfaceAttribExternalBuffers like so

GstVideoInfo video_info;

VASurfaceAttribExternalBuffers extern_buf;
  memset(&extern_buf, 0, sizeof(VASurfaceAttribExternalBuffers));
  extern_buf.buffers = new unsigned long[1]; 
  extern_buf.buffers[0] = reinterpret_cast<unsigned long>(i420_data);
  extern_buf.num_buffers = 1;
  extern_buf.width =width;
  extern_buf.height = height;
  extern_buf.num_planes =video_info.n_planes;
  extern_buf.data_size = video_info.size;
  for (int i = 0; i < 4; i++) {
    extern_buf.pitches[i] = video_info.stride[i];
    extern_buf.offsets[i] = video_info.offset[i];
  }
  extern_buf.pixel_format = pixel_format;

calling vaCreateSurfaces() will result in "resource allocation failure". It has to do with the extern_buf.data_size. If if set the data size to width * height, the call is successful. but then only the first plane is valid. 
Any idea what am I doing wrong ?

**Comment by dvrogozh** [comment]
You asked this question in libva. Please, provide answer on questions from this comment: https://github.com/intel/libva/issues/326#issuecomment-520578078. Posting it here as well:

How original i420 memory was allocated? Mind that userptr path has 2 basic requirements:

Pointer should be page aligned
Data size should be page aligned
There are other requirements implied by the media-driver, but the above 2 are basic ones. As for the media-driver requirements, the following would likely be supreme requirements:

Width should be 16-aligned
Height should be 4-aligned
Pitch should be 64-aligned
I afraid, however, there could be some issues in a media-driver on the userptr path since this is rarely used path. Please, share anything you will come across with us.

**Comment by XinfengZhang** [comment]
no response, the USER_PTR should works if the allocation of system memory is aligned with the requirements
