### ISSUE TITLE
[mb_bd_rate_control][ffmpeg][vaapi] get poor quality if mb_rate_control is enabled

### ISSUE THREAD

**Issue by fulinjie** [intel/media-driver#825]
CMDline:
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -r:v 30 -f rawvideo -s:v 352x288 -pix_fmt yuv420p -i MOBILE_352x288_30_orig_01_352x288_I420.yuv -vf format=nv12,hwupload -c:v hevc_vaapi -profile:v main -low_power 1 -b:v 100k -maxrate 100k -vframes 300 -y vaapi_lp.h265

The quality (bd-rate) become poor if we explicitly enable mb_rate_control.

**Comment by Xiaogangli-intel** [comment]
Which platform are you working on?

**Comment by XinfengZhang** [comment]
ideally , mb_rate_control will enable MB BRC , which will reduce bitstream size with same quality, but sometimes, it is already enabled by default inside driver.  because no platform mentioned in the issue description , @Xiaogangli-intel , could we try the command on TGL, and check the difference, if there are no such issue, we could close it. thanks

**Comment by Xiaogangli-intel** [comment]
Close it, no activities for more than 9 months.
