### ISSUE TITLE
What's the difference from https://github.com/intel/intel-vaapi-driver

### ISSUE THREAD

**Issue by YijinLiu** [intel/media-driver#97]
I am using https://github.com/intel/intel-vaapi-driver now. I wonder what's the advantages this new driver provides. Should I switch to it?

**Comment by YijinLiu** [comment]
We are mainly using vaapi to decode / encode h264/vp8 on Goldmont/Skylake. Is there any performance difference between the two drivers? Like cpu/gpu/memory usage or video quality/compression ratio.

**Comment by mypopydev** [comment]
@YijinLiu I think now media-driver can't support VP8 encode in Skylake, so I guess maybe i965 is the only  choice in this case.

**Comment by XinfengZhang** [comment]
Initial releases of the Intel® Media Driver for VAAPI  will track close with Intel vaapi media driver features, quality and performance.  It is expected that future release with focus from Intel and the community will deliver best in class features, quality and performance.

**Comment by enihcam** [comment]
@XinfengZhang 
My notebook is KabyLake based, and in the most of time it is just used for decoding video, so in performance/power-consumption aspects which driver should I use?

Additionally, in wiki can you create a table sheet to list the mappings between processors and drivers?

**Comment by francoism90** [comment]
Any update on this? Does one need both on supported platforms?

**Comment by XinfengZhang** [comment]
no need both, you can just choose either for current platform, but in future, from CNL+, only media_driver exist. no intel-vaapi-driver for CNL+ platform.

**Comment by enihcam** [comment]
@XinfengZhang I exported chromium-vaapi GPU reports for both drivers, and found that intel-media-driver supports VP9 hardware acceleration, but intel-vaapi-driver does not. My processor is i5-7200U.

**Comment by sandsmark** [comment]
here on whiskey lake both intel-vaapi-driver and intel-media-driver reports to support vp9 via vainfo, and intel-vaapi-driver reports decoding support for two more formats (VAProfileH264StereoHigh and VAProfileH264MultiviewHigh).

Testing with a VP9 test video from https://test-videos.co.uk/bigbuckbunny/webm-vp9 with mpv I get the same CPU usage with both intel-vaapi-driver and intel-media-driver as well.

Am I missing something? The reason I started looking at this is because I get this seemingly harmless error now; `[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).`
